### ISSUE TITLE
Запуск примеров

### ISSUE THREAD

**Issue by AnnBerg** [WISEPLAT/Learn-BackTrader#1]
Доброго времени суток. Помогите, пожалуйста, разобраться. По какой-то причине не приходят бары при запуске примеров из этого репозитория. При запуске примеров QuikPy всё работает.  Ниже некоторый вывод в консоль и трейсбек ошибки:
```python 
#Learn-BackTrader/get_all_shares_ok_quik.py
Подключено к терминалу QUIK по адресу: 127.0.0.1:34130,34131
Экземпляры класса совпадают: False
Терминал QUIK подключен к серверу: True
newBars:  TQBR|ROSN|60|0
Traceback (most recent call last):
  File "c:\:\PATHtrade\Learn-BackTrader\get_all_shares_ok_quik.py", line 76, in <module>
    load_data.ExportToCsvFromQuik(qpProvider, _ticker, timeframe, utc_till, how_many_bars,
  File "c:\:\PATHLearn-BackTrader\SharesDataLoader\DataQuik.py", line 142, in ExportToCsvFromQuik
    df = self.GetShareDataFromQuik(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\PATH\trade\Learn-BackTrader\SharesDataLoader\DataQuik.py", line 77, in GetShareDataFromQuik
    pdBars = pd.DataFrame.from_dict(pd.json_normalize(newBars),
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PATH\Lib\site-packages\pandas\io\json\_normalize.py", line 447, in json_normalize
    raise NotImplementedError
NotImplementedError
```

**Comment by WISEPLAT** [comment]
Добрый вечер) Этот код просто уже устарел - т.к. автор библиотеки поменял названия методов. Там есть новые примеры кода.
